Areas/Admin/Controllers/AdminKhachhangsController.cs
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using doan.Models;
using PagedList.Core;

namespace doan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminKhachhangsController : Controller
    {
        private readonly CuaHangDecorateContext _context;

        public AdminKhachhangsController(CuaHangDecorateContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminKhachhangs
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Khachhang.ToListAsync());
        //}
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var IsKhachhangs = _context.Khachhang.AsNoTracking()
                .OrderBy(x => x.MaKh);
            PagedList<Khachhang> models = new PagedList<Khachhang>(IsKhachhangs, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminKhachhangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachhang = await _context.Khachhang
                .FirstOrDefaultAsync(m => m.MaKh == id);
            if (khachhang == null)
            {
                return NotFound();
            }

            return View(khachhang);
        }

        // GET: Admin/AdminKhachhangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminKhachhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKh,TenKh,SoDienThoai,NgaySinh,GioiTinh,DiaChi,LoaiKh")] Khachhang khachhang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(khachhang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(khachhang);
        }

        // GET: Admin/AdminKhachhangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachhang = await _context.Khachhang.FindAsync(id);
            if (khachhang == null)
            {
                return NotFound();
            }
            return View(khachhang);
        }

        // POST: Admin/AdminKhachhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaKh,TenKh,SoDienThoai,NgaySinh,GioiTinh,DiaChi,LoaiKh")] Khachhang khachhang)
        {
            if (id != khachhang.MaKh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachhang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachhangExists(khachhang.MaKh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(khachhang);
        }

        // GET: Admin/AdminKhachhangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachhang = await _context.Khachhang
                .FirstOrDefaultAsync(m => m.MaKh == id);
            if (khachhang == null)
            {
                return NotFound();
            }

            return View(khachhang);
        }

        // POST: Admin/AdminKhachhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var khachhang = await _context.Khachhang.FindAsync(id);
            _context.Khachhang.Remove(khachhang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachhangExists(int id)
        {
            return _context.Khachhang.Any(e => e.MaKh == id);
        }
    }
}

Areas/Admin/Views/AdminKhachhangs/Create.cshtml
@model doan.Models.Khachhang 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Khachhang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenKh" class="control-label"></label>
                <input asp-for="TenKh" class="form-control" />
                <span asp-validation-for="TenKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label"></label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiKh" class="control-label"></label>
                <input asp-for="LoaiKh" class="form-control" />
                <span asp-validation-for="LoaiKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminKhachhangs/Delete.cshtml
@model doan.Models.Khachhang 

@{
    ViewData["Title"] = "Xác nhận xóa thông tin khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Index">Danh sách khách hàng</a>
            <span class="breadcrumb-item active">Xác nhận xóa thông tin khách hàng</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xác nhận xóa thông tin khách hàng</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaKh</td>
                    </tr>
                    <tr>
                        <td>Tên khách hàng:</td>
                        <td>@Model.TenKh</td>
                    </tr>
                    <tr>
                        <td>Số điện thoại:</td>
                        <td>@Model.SoDienThoai</td>
                    </tr>
                    <tr>
                        <td>Ngày sinh:</td>
                        <td>@String.Format("{0:dd/MM/yyyy}", Model.NgaySinh)</td>
                    </tr>
                    <tr>
                        <td>Giới tính:</td>
                        <td>@Model.GioiTinh</td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.DiaChi</td>
                    </tr>
                    <tr>
                        <td>Loại khách hàng:</td>
                        <td>@Model.LoaiKh</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="MaKh" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> 
                                
                            </form>

                        </td>

                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminKhachhangs/Details.cshtml
@model doan.Models.Khachhang 

@{
    ViewData["Title"] = "Thông tin khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Index">Danh sách khách hàng</a>
            <span class="breadcrumb-item active">Thông tin khách hàng</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin khách hàng</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaKh</td>
                    </tr>
                    <tr>
                        <td>Tên khách hàng:</td>
                        <td>@Model.TenKh</td>
                    </tr>
                    <tr>
                        <td>Số điện thoại:</td>
                        <td>@Model.SoDienThoai</td>
                    </tr>
                    <tr>
                        <td>Ngày sinh:</td>
                        <td>@String.Format("{0:dd/MM/yyyy}", Model.NgaySinh)</td>
                    </tr>
                    <tr>
                        <td>Giới tính:</td>
                        <td>@Model.GioiTinh</td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.DiaChi</td>
                    </tr>
                    <tr>
                        <td>Loại khách hàng:</td>
                        <td>@Model.LoaiKh</td>
                    </tr>



                </tbody>
            </table>
        </div>
    </div>
</div>
@*<h1>Details</h1>

    <div>
        <h4>Khachhang</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.TenKh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TenKh)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.SoDienThoai)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.NgaySinh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.NgaySinh)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.GioiTinh)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.DiaChi)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.LoaiKh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.LoaiKh)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.MaKh">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

Areas/Admin/Views/AdminKhachhangs/Edit.cshtml
@model doan.Models.Khachhang 

@{
    ViewData["Title"] = "Chỉnh sửa thông tin khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Index">Danh sách khách hàng</a>
            <span class="breadcrumb-item active">Chỉnh sửa thông tin khách hàng</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaKh" />
            <div class="form-group">
                <label asp-for="TenKh" class="control-label">Tên khách hàng</label>
                <input asp-for="TenKh" class="form-control" />
                <span asp-validation-for="TenKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label">Số điện thoại</label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label">Ngày sinh</label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label">Giới tính</label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label">Địa chỉ</label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiKh" class="control-label">Loại khách hàng</label>
                <input asp-for="LoaiKh" class="form-control" />
                <span asp-validation-for="LoaiKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminKhachhangs/Index.cshtml
@*@model IEnumerable<doan.Models.Khachhang>*@ 
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<doan.Models.Khachhang>
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách khách hàng" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>

            <span class="breadcrumb-item active">Danh sách khách hàng : trang @CurrentPage </span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        @*<div class="row m-b-30">
            <div class="col-lg-12">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Catergory</option>
                            <option value="all">All</option>
                            <option value="homeDeco">Home Decoration</option>
                            <option value="eletronic">Eletronic</option>
                            <option value="jewellery">Jewellery</option>
                        </select>
                    </div>
                    <div class="m-b-10">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Status</option>
                            <option value="all">All</option>
                            <option value="inStock">In Stock </option>
                            <option value="outOfStock">Out of Stock</option>
                        </select>
                    </div>
                </div>
            </div>

        </div>*@
        @*<div class="row m-b-30">
            <div class="col-md-8">
            </div>

            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminKhachhangs" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm khách hàng</span></a>

            </div>
        </div>*@
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>ID</th>
                        <th>Tên khách hàng</th>
                        <th>Số điện thoại</th>
                        <th>Ngày sinh</th>
                        <th> Giới tính</th>
                        <th>Địa chỉ</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)

                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @item.MaKh
                                </td>
                                <td>
                                    @item.TenKh
                                </td>
                                <td>@item.SoDienThoai</td>
                                <td>@String.Format("{0:dd/MM/yyyy}", item.NgaySinh)</td>
                                <td>@item.GioiTinh</td>
                                <td>@item.DiaChi</td>


                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Details" asp-route-id="@item.MaKh">Chi tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Edit" asp-route-id="@item.MaKh">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Delete" asp-route-id="@item.MaKh">Xóa</a>


                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminKhachhangs" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>