Areas/Admin/Controllers/AdminDanhmucspsController.cs
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using doan.Models;
using PagedList.Core;

namespace doan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminDanhmucspsController : Controller
    {
        private readonly CuaHangDecorateContext _context;

        public AdminDanhmucspsController(CuaHangDecorateContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminDanhmucsps
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Danhmucsp.ToListAsync());
        //}
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var IsDanhmucsanphams = _context.Danhmucsp.AsNoTracking()
                .OrderBy(x => x.MaDanhMuc);
            PagedList<Danhmucsp> models = new PagedList<Danhmucsp>(IsDanhmucsanphams, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminDanhmucsps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmucsp = await _context.Danhmucsp
                .FirstOrDefaultAsync(m => m.MaDanhMuc == id);
            if (danhmucsp == null)
            {
                return NotFound();
            }

            return View(danhmucsp);
        }

        // GET: Admin/AdminDanhmucsps/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminDanhmucsps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDanhMuc,TenDanhMuc,MoTa")] Danhmucsp danhmucsp)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhmucsp);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(danhmucsp);
        }

        // GET: Admin/AdminDanhmucsps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmucsp = await _context.Danhmucsp.FindAsync(id);
            if (danhmucsp == null)
            {
                return NotFound();
            }
            return View(danhmucsp);
        }

        // POST: Admin/AdminDanhmucsps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaDanhMuc,TenDanhMuc,MoTa")] Danhmucsp danhmucsp)
        {
            if (id != danhmucsp.MaDanhMuc)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhmucsp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhmucspExists(danhmucsp.MaDanhMuc))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(danhmucsp);
        }

        // GET: Admin/AdminDanhmucsps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhmucsp = await _context.Danhmucsp
                .FirstOrDefaultAsync(m => m.MaDanhMuc == id);
            if (danhmucsp == null)
            {
                return NotFound();
            }

            return View(danhmucsp);
        }

        // POST: Admin/AdminDanhmucsps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhmucsp = await _context.Danhmucsp.FindAsync(id);
            _context.Danhmucsp.Remove(danhmucsp);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DanhmucspExists(int id)
        {
            return _context.Danhmucsp.Any(e => e.MaDanhMuc == id);
        }
    }
}

Areas/Admin/Views/AdminDanhmucsps/Create.cshtml
@model doan.Models.Danhmucsp 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Index">Danh sách danh mục</a>
            <span class="breadcrumb-item active">Tạo danh mục sản phẩm</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenDanhMuc" class="control-label">Tên danh mục</label>
                <input asp-for="TenDanhMuc" class="form-control" />
                <span asp-validation-for="TenDanhMuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label">Mô tả</label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminDanhmucsps/Delete.cshtml
@model doan.Models.Danhmucsp 

@{
    ViewData["Title"] = "Xác nhận xóa danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Index">Danh sách danh mục sản phẩm</a>
            <span class="breadcrumb-item active">Xác nhận xóa danh mục sản phẩm</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xác nhận xóa danh mục sản phẩm</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaDanhMuc</td>
                    </tr>
                    <tr>
                        <td>Tên danh mục:</td>
                        <td>@Model.TenDanhMuc</td>
                    </tr>

                    <tr>
                        <td>Mô tả danh mục:</td>
                        <td>@Model.MoTa</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="MaDanhMuc" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> 
                                
                            </form>
                        </td>

                    </tr>



                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminDanhmucsps/Details.cshtml
@model doan.Models.Danhmucsp
 
@{
    ViewData["Title"] = "Thông tin danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@*<h1>Details</h1>

    <div>
        <h4>Danhmucsp</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.TenDanhMuc)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TenDanhMuc)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.MoTa)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.MoTa)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.MaDanhMuc">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Index">Danh sách danh mục sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin danh mục sản phẩm</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin danh mục sản phẩm</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaDanhMuc</td>
                    </tr>
                    <tr>
                        <td>Tên danh mục:</td>
                        <td>@Model.TenDanhMuc</td>
                    </tr>
                    
                    <tr>
                        <td>Mô tả danh mục:</td>
                        <td>@Model.MoTa</td>
                    </tr>
                    



                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminDanhmucsps/Edit.cshtml
@model doan.Models.Danhmucsp 

@{
    ViewData["Title"] = "Chỉnh sửa danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Index">Danh sách danh mục</a>
            <span class="breadcrumb-item active">Chỉnh sửa danh mục</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaDanhMuc" />
            <div class="form-group">
                <label asp-for="TenDanhMuc" class="control-label">Tên danh mục</label>
                <input asp-for="TenDanhMuc" class="form-control" />
                <span asp-validation-for="TenDanhMuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label">Mô tả</label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminDanhmucsps/Index.cshtml
@using PagedList.Core.Mvc 
@model PagedList.Core.IPagedList<doan.Models.Danhmucsp>
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách danh mục" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>

            <span class="breadcrumb-item active">Danh sách danh mục : trang @CurrentPage </span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">

        @*<div class="row">
            <div class="col-md-6">
                <div class="input-affix m-v-10">
                    <i class="prefix-icon anticon anticon-search opacity-04"></i>
                    <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm sản phẩm" />
                </div>

            </div>
            <div class="col-md-6">
                <div class="input-affix m-v-10">
                    <select id="madanhmuc" name="madanhmuc" class="custom-select" style="min-width: 200px;" asp-items="ViewBag.Danhmuc">
                        <option selected>Chọn danh mục sản phẩm</option>
                        <option value="all">Chọn tất cả</option>
                    </select>
                </div>

            </div>

        </div>*@
        <div class="row m-b-30">
            <div class="col-md-8">
            </div>

            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminDanhmucsps" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm danh mục</span></a>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>ID</th>
                        <th>Tên danh mục</th>
                        <th>Mô tả</th>

                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)

                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @item.MaDanhMuc
                                </td>
                                <td>
                                    @item.TenDanhMuc
                                </td>
                                <td>@item.MoTa</td>




                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Details" asp-route-id="@item.MaDanhMuc">Chi tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Edit" asp-route-id="@item.MaDanhMuc">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Delete" asp-route-id="@item.MaDanhMuc">Xóa</a>


                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminDanhmucsps" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>