Areas/Admin/Controllers/AdminHinhanhsController.cs
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using doan.Models;
using PagedList.Core;
using System.IO;
using doan.Helpper;
using Microsoft.AspNetCore.Http;

namespace doan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminHinhanhsController : Controller
    {
        private readonly CuaHangDecorateContext _context;

        public AdminHinhanhsController(CuaHangDecorateContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminHinhanhs
        //public async Task<IActionResult> Index()
        //{
        //    var cuaHangDecorateContext = _context.Hinhanh.Include(h => h.MaSpNavigation);
        //    return View(await cuaHangDecorateContext.ToListAsync());
        //}
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var IsHinhanhs = _context.Hinhanh
                .AsNoTracking()
                .Include(x => x.MaSpNavigation)
                .OrderBy(x => x.MaHinhAnh);
            PagedList<Hinhanh> models = new PagedList<Hinhanh>(IsHinhanhs, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminHinhanhs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hinhanh = await _context.Hinhanh
                .Include(h => h.MaSpNavigation)
                .FirstOrDefaultAsync(m => m.MaHinhAnh == id);
            if (hinhanh == null)
            {
                return NotFound();
            }

            return View(hinhanh);
        }

        // GET: Admin/AdminHinhanhs/Create
        public IActionResult Create()
        {
            
            ViewData["MaSp"] = new SelectList(_context.Sanpham, "MaSp", "TenSp");
            return View();
        }

        // POST: Admin/AdminHinhanhs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaHinhAnh,LinkHinhAnh,MaSp")] Hinhanh hinhanh, IFormFile myfile)// Microsoft.AspNetCore.Http.IFormFile fLinkHinhAnh)
        {
            if (ModelState.IsValid)
            {
                if (myfile != null)
                {
                    string fullPath = Path.Combine(Directory.GetCurrentDirectory(),
                                        "wwwroot", "Image", myfile.FileName);
                    using (var file = new FileStream(fullPath, FileMode.Create))
                    {
                        myfile.CopyTo(file);
                    }
                }
                  hinhanh.LinkHinhAnh = myfile.FileName;

                //hinhanh.MaSpNavigation.TenSp = Utilities.ToTitleCase(hinhanh.MaSpNavigation.TenSp);
                //if (fLinkHinhAnh != null)
                //{
                //    string extension = Path.GetExtension(fLinkHinhAnh.FileName);
                //    string image = Utilities.SEOUrl(hinhanh.MaSpNavigation.TenSp) + extension;
                //    hinhanh.LinkHinhAnh = await Utilities.UploadFile(fLinkHinhAnh, @"Hinh_anh_san_pham", extension.ToLower());
                //}
                //if (string.IsNullOrEmpty(hinhanh.LinkHinhAnh)) hinhanh.LinkHinhAnh = "default.jpg";
                _context.Add(hinhanh);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.Sanpham, "MaSp", "TenSp", hinhanh.MaSp);
            return View(hinhanh);
        }

        // GET: Admin/AdminHinhanhs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hinhanh = await _context.Hinhanh.FindAsync(id);
            if (hinhanh == null)
            {
                return NotFound();
            }
            ViewData["MaSp"] = new SelectList(_context.Sanpham, "MaSp", "TenSp", hinhanh.MaSp);
            return View(hinhanh);
        }

        // POST: Admin/AdminHinhanhs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHinhAnh,LinkHinhAnh,MaSp")] Hinhanh hinhanh)
        {
            if (id != hinhanh.MaHinhAnh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hinhanh);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HinhanhExists(hinhanh.MaHinhAnh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaSp"] = new SelectList(_context.Sanpham, "MaSp", "TenSp", hinhanh.MaSp);
            return View(hinhanh);
        }

        // GET: Admin/AdminHinhanhs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hinhanh = await _context.Hinhanh
                .Include(h => h.MaSpNavigation)
                .FirstOrDefaultAsync(m => m.MaHinhAnh == id);
            if (hinhanh == null)
            {
                return NotFound();
            }

            return View(hinhanh);
        }

        // POST: Admin/AdminHinhanhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hinhanh = await _context.Hinhanh.FindAsync(id);
            _context.Hinhanh.Remove(hinhanh);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HinhanhExists(int id)
        {
            return _context.Hinhanh.Any(e => e.MaHinhAnh == id);
        }
    }
}

Areas/Admin/Views/AdminHinhanhs/Create.cshtml
@model doan.Models.Hinhanh

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Index">Danh sách hình ảnh</a>
            <span class="breadcrumb-item active">Thêm hình ảnh</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="AdminHinhanhs" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LinkHinhAnh" class="control-label">Chọn hình ảnh</label>
                <input name="myfile" type="file" asp-for="LinkHinhAnh" class="form-control-file" />
                <span asp-validation-for="LinkHinhAnh" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="MaSp" class="control-label">Tên sản phẩm</label>
                <select asp-for="MaSp" class="form-control" asp-items="ViewBag.MaSp"></select>

            </div>
            <div class="form-group">
                <input type="submit" value="Tạo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>*@
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminHinhanhs/Delete.cshtml
@model doan.Models.Hinhanh 

@{
    ViewData["Title"] = "Xác nhận xóa hình ảnh";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Index">Danh sách hình ảnh</a>
            <span class="breadcrumb-item active">Xác nhận xóa hình ảnh</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xác nhận xóa hình ảnh</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaHinhAnh</td>
                    </tr>
                    <tr>
                        <td>Link hình ảnh:</td>
                        <td>@Model.LinkHinhAnh</td>
                    </tr>

                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>@Model.MaSpNavigation.TenSp</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="MaHinhAnh" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> 
                               
                            </form>
                        </td>

                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminHinhanhs/Details.cshtml
@model doan.Models.Hinhanh 

@{
    ViewData["Title"] = "Thông tin hình ảnh";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@*<h1>Details</h1>

    <div>
        <h4>Hinhanh</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.LinkHinhAnh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.LinkHinhAnh)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.MaSpNavigation)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.MaSpNavigation.TenSp)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.MaHinhAnh">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@


<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Index">Danh sách hình ảnh</a>
            <span class="breadcrumb-item active">Thông tin hình ảnh</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin hình ảnh</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaHinhAnh</td>
                    </tr>
                    <tr>
                        <td>Link hình ảnh:</td>
                        <td>@Model.LinkHinhAnh</td>
                    </tr>
                    
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>@Model.MaSpNavigation.TenSp</td>
                    </tr>



                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminHinhanhs/Edit.cshtml
@model doan.Models.Hinhanh 

@{
    ViewData["Title"] = "Chỉnh sửa hình ảnh";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Index">Danh sách hình ảnh</a>
            <span class="breadcrumb-item active">Chỉnh sửa hình ảnh</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaHinhAnh" />
            <div class="form-group">
                <label asp-for="LinkHinhAnh" class="control-label">Link hình ảnh</label>
                <input asp-for="LinkHinhAnh" class="form-control" />
                <span asp-validation-for="LinkHinhAnh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaSp" class="control-label">Tên sản phẩm</label>
                <select asp-for="MaSp" class="form-control" asp-items="ViewBag.MaSp"></select>
                <span asp-validation-for="MaSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminHinhanhs/Index.cshtml
@using PagedList.Core.Mvc 
@model PagedList.Core.IPagedList<doan.Models.Hinhanh>
@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách hình ảnh" + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>

            <span class="breadcrumb-item active">Danh sách hình ảnh : trang @CurrentPage </span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-md-8">


            </div>

            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminHinhanhs" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm hình ảnh</span></a>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>ID</th>
                        <th>Link</th>
                        <th>Tên sản phẩm</th>

                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)

                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @item.MaHinhAnh
                                </td>
                                <td>

                                    @if (item.LinkHinhAnh == null)

                                    {
                                        var temp = "";
                                        @temp;

                                    }
                                    else
                                   if (item.LinkHinhAnh.Length > 20)

                                    {
                                        var temp = item.LinkHinhAnh.Substring(0, 20) + "...";
                                        @temp;
                                    }
                                    else
                                    {
                                        @item.LinkHinhAnh
                                    }

                                </td>
                                <td>@item.MaSpNavigation.TenSp</td>




                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Details" asp-route-id="@item.MaHinhAnh">Chi tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Edit" asp-route-id="@item.MaHinhAnh">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Delete" asp-route-id="@item.MaHinhAnh">Xóa</a>


                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminHinhanhs" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
    </div>