Areas/Admin/Controllers/AdminNhanviensController.cs
using System; 
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using doan.Models;

namespace doan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminNhanviensController : Controller
    {
        private readonly CuaHangDecorateContext _context;

        public AdminNhanviensController(CuaHangDecorateContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminNhanviens
        public async Task<IActionResult> Index()
        {
            

            return View(await _context.Nhanvien.ToListAsync());
        }

        // GET: Admin/AdminNhanviens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }

            var nhanvien = await _context.Nhanvien
                .FirstOrDefaultAsync(m => m.MaNv == id);
            if (nhanvien == null)
            {
                return NotFound();
            }

            return View(nhanvien);
        }

        // GET: Admin/AdminNhanviens/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminNhanviens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaNv,TenNv,SoDienThoai,NgaySinh,GioiTinh,DiaChi,NgayVaoLam,ChucVu")] Nhanvien nhanvien)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nhanvien);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nhanvien);
        }

        // GET: Admin/AdminNhanviens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanvien = await _context.Nhanvien.FindAsync(id);
            if (nhanvien == null)
            {
                return NotFound();
            }
            return View(nhanvien);
        }

        // POST: Admin/AdminNhanviens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaNv,TenNv,SoDienThoai,NgaySinh,GioiTinh,DiaChi,NgayVaoLam,ChucVu")] Nhanvien nhanvien)
        {
            if (id != nhanvien.MaNv)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nhanvien);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NhanvienExists(nhanvien.MaNv))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nhanvien);
        }

        // GET: Admin/AdminNhanviens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nhanvien = await _context.Nhanvien
                .FirstOrDefaultAsync(m => m.MaNv == id);
            if (nhanvien == null)
            {
                return NotFound();
            }

            return View(nhanvien);
        }

        // POST: Admin/AdminNhanviens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nhanvien = await _context.Nhanvien.FindAsync(id);
            _context.Nhanvien.Remove(nhanvien);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NhanvienExists(int id)
        {
            return _context.Nhanvien.Any(e => e.MaNv == id);
        }
    }
}

Areas/Admin/Views/AdminNhanviens/Create.cshtml
@model doan.Models.Nhanvien 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Index">Danh sách nhân viên</a>
            <span class="breadcrumb-item active">Thêm nhân viên</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenNv" class="control-label">Tên nhân viên</label>
                <input asp-for="TenNv" class="form-control" />
                <span asp-validation-for="TenNv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label">Số điện thoại</label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label">Ngày sinh</label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label">Giới tính</label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label">Địa chỉ</label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayVaoLam" class="control-label">Ngày vào làm</label>
                <input asp-for="NgayVaoLam" class="form-control" />
                <span asp-validation-for="NgayVaoLam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChucVu" class="control-label">Chức vụ</label>
                <input asp-for="ChucVu" class="form-control" />
                <span asp-validation-for="ChucVu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminNhanviens/Delete.cshtml
@model doan.Models.Nhanvien 

@{
    ViewData["Title"] = "Xác nhận xóa nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Index">Danh sách nhân viên</a>
            <span class="breadcrumb-item active">Xác nhận xóa nhân viên</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xác nhận xóa nhân viên</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaNv</td>
                    </tr>
                    <tr>
                        <td>Tên khách hàng:</td>
                        <td>@Model.TenNv</td>
                    </tr>
                    <tr>
                        <td>Số điện thoại:</td>
                        <td>@Model.SoDienThoai</td>
                    </tr>
                    <tr>
                        <td>Ngày sinh:</td>
                        <td>@String.Format("{0:dd/MM/yyyy}", Model.NgaySinh)</td>
                    </tr>
                    <tr>
                        <td>Giới tính:</td>
                        <td>@Model.GioiTinh</td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.DiaChi</td>
                    </tr>
                    <tr>
                        <td>Ngày vào làm:</td>
                        <td>@String.Format("{0:dd/MM/yyyy}", Model.NgayVaoLam)</td>
                    </tr>
                    <tr>
                        <td>Chức vụ:</td>
                        <td>@Model.ChucVu</td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa:</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="MaNv" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> 
                            </form>
                        </td>

                    </tr>


                </tbody>
            </table>
        </div>
    </div>
</div>

Areas/Admin/Views/AdminNhanviens/Details.cshtml
@model doan.Models.Nhanvien 

@{
    ViewData["Title"] = "Thông tin nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Index">Danh sách nhân viên</a>
            <span class="breadcrumb-item active">Thông tin nhân viên</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin nhân viên</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaNv</td>
                    </tr>
                    <tr>
                        <td>Tên khách hàng:</td>
                        <td>@Model.TenNv</td>
                    </tr>
                    <tr>
                        <td>Số điện thoại:</td>
                        <td>@Model.SoDienThoai</td>
                    </tr>
                    <tr>
                        <td>Ngày sinh:</td>
                        <td>@String.Format("{0:dd/MM/yyyy}", Model.NgaySinh)</td>
                    </tr>
                    <tr>
                        <td>Giới tính:</td>
                        <td>@Model.GioiTinh</td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Model.DiaChi</td>
                    </tr>
                    <tr>
                        <td>Ngày vào làm:</td>
                        <td>@String.Format("{0:dd/MM/yyyy}", Model.NgayVaoLam)</td>
                    </tr>
                    <tr>
                        <td>Chức vụ:</td>
                        <td>@Model.ChucVu</td>
                    </tr>



                </tbody>
            </table>
        </div>
    </div>
</div>
@*<h1>Details</h1>

    <div>
        <h4>Nhanvien</h4>
        <hr />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.TenNv)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.TenNv)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.SoDienThoai)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.NgaySinh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.NgaySinh)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.GioiTinh)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.GioiTinh)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.DiaChi)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.DiaChi)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.NgayVaoLam)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.NgayVaoLam)
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.ChucVu)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ChucVu)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.MaNv">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

Areas/Admin/Views/AdminNhanviens/Edit.cshtml
@model doan.Models.Nhanvien 

@{
    ViewData["Title"] = "Chỉnh sửa thông tin nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">

    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Index">Danh sách nhân viên</a>
            <span class="breadcrumb-item active">Chỉnh sửa thông tin nhân viên</span>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaNv" />
            <div class="form-group">
                <label asp-for="TenNv" class="control-label">Tên nhân viên</label>
                <input asp-for="TenNv" class="form-control" />
                <span asp-validation-for="TenNv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label">Số điện thoại</label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label">Ngày sinh</label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiTinh" class="control-label">Giới tính</label>
                <input asp-for="GioiTinh" class="form-control" />
                <span asp-validation-for="GioiTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label">Địa chỉ</label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayVaoLam" class="control-label">Ngày vào làm</label>
                <input asp-for="NgayVaoLam" class="form-control" />
                <span asp-validation-for="NgayVaoLam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChucVu" class="control-label">Chức vụ</label>
                <input asp-for="ChucVu" class="form-control" />
                <span asp-validation-for="ChucVu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminNhanviens/Index.cshtml
@model IEnumerable<doan.Models.Nhanvien> 

@{
    ViewData["Title"] = "Danh sách nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>

            <span class="breadcrumb-item active">Danh sách nhân viên</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-md-8">
            </div>

            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminNhanviens" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm nhân viên</span></a>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>

                        <th>ID</th>
                        <th>Tên nhân viên</th>
                        <th>SDT</th>
                        <th>Ngày sinh</th>
                        <th> Ngày vào làm</th>
                        
                        <th>Địa chỉ</th>

                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)

                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @item.MaNv
                                </td>
                                <td>
                                    @item.TenNv
                                </td>
                                <td>@item.SoDienThoai</td>
                                <td>@String.Format("{0:dd/MM/yyyy}", item.NgaySinh)</td>
                                <td>@String.Format("{0:dd/MM/yyyy}", item.NgayVaoLam)</td>

                                
                                <td>@item.DiaChi</td>


                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Details" asp-route-id="@item.MaNv">Chi tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Edit" asp-route-id="@item.MaNv">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminNhanviens" asp-action="Delete" asp-route-id="@item.MaNv">Xóa</a>


                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            
        </div>
    </div>
</div>